"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const cargo_1 = require("./classes/cargo");
const funcionario_1 = require("./classes/funcionario");
//Crie dois funcionários do banco, um gerente e um atendente.
const cargoGerente = new cargo_1.Cargo("Gerente");
const cargoAtendente = new cargo_1.Cargo("Atendente");
const func1 = new funcionario_1.Funcionario("99999999970", "Danilo", "8888-8888", 5000, cargoGerente);
const func2 = new funcionario_1.Funcionario("99999999990", "Felipe", "8888-8888", 2000, cargoAtendente);
console.log(func1.cpf, func1.nome, func1.telefone, func1.salario, func1.cargo, func1.autenticar());
console.log("----------------------------------");
console.log(func2.cpf, func2.nome, func2.telefone, func2.salario, func2.cargo, func2.autenticar());
console.log("----------------------------------");
console.log(cargoGerente);
console.log("----------------------------------");
console.log(cargoAtendente);
console.log("----------------------------------");
console.log(func1);
console.log("----------------------------------");
console.log(func2);
